### ISSUE TITLE
persistent db connection

### ISSUE THREAD

**Issue by facutk** [schadokar/go-postgres#2]
Do you think it's ok that you open a connection each time you handle an event?
Wouldn't it be faster and thread safer to open connection pool and consume from there?

**Comment by schadokar** [comment]
Yes, we should close the connection as soon as possible.  
If the request depends on multiple db interactions then open it once, complete all the request and close it. Don't keep it open for future requests. 
Please search why should you close the db connection?

**Comment by facutk** [comment]
My question was on the other side... why not do something like this

instead of a single connection, create a pool of connections
https://github.com/facutk/golaburo/blob/main/main.go#L19

and then on the handles, grab from that pool of connections
https://github.com/facutk/golaburo/blob/main/api/todos/todos.go#L24

**Comment by schadokar** [comment]
With this approach your db connection is open till main.go exit. This is not recommended and there going to be security issues too. For each request, if you open and close the connection, then you can check authorization and validity of request before connecting to DB.
